name: Lint and Deploy static site

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  lint_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run ESLint
        run: eslint "site/**/*.js"

      - name: Run HTMLHint
        run: htmlhint "site/**/*.html"

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::017820667577:role/SecureStaticSiteCICDRole
          aws-region: eu-west-1

      - name: Deploy static site to S3
        run: aws s3 sync ./site/ s3://secure-website-lrccosta/ --delete
